[package]
name = "ccsds_spoof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
ccsds_primary_header = "0.15.0"
pretty-hex = "0.2.1"
rustc-hex = "2.1.0"
