[package]
name = "fits_spoof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fits-rs = { path="fits-rs"}
nom = "5.0.0"
