[package]
name = "ssh_parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh-parser = "0.5.0"
strum = "0.21.0"
nom = "7.0.0"
