[package]
name = "slm_dhcpparse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhcp-parser2 = { path="dhcp-parser"}
